
# Site
title: Father AI
subtitle: Father AI Blog
subtitle_desc: A blog for shared knowlege in AI
keywords: AI, deeplearning, RL, dnn
description: Dedicated to sharing the latest achievements and experience in artificial intelligence
introduction: Dedicated to sharing the latest achievements and experience in artificial intelligence
favicon_ico: http://oo12ugek5.bkt.clouddn.com/blog/images/favicon.ico

logo: /img/kingsoft_logo.png

qrcode: http://oo12ugek5.bkt.clouddn.com/images/qrcode.png
default_cover: https://www.seoclerk.com/pics/550925-1fY25w1502215384.jpg #http://oo12ugek5.bkt.clouddn.com/images/default_cover.png

header_cover: /img/ai_banner.jpg #http://oo12ugek5.bkt.clouddn.com/blog/images/banner.jpeg
error_page_bg: http://oo12ugek5.bkt.clouddn.com/blog/images/dogs.jpg

author:
  name: Yi Gu
  link: https://github.com/tornadoyi

about:
  info: Dedicated to sharing the latest achievements and experience in artificial intelligence
  address: Shang Di, Beijing Province, China
  email: guyi@kingsoft.com

# Menu
menu:
  home: / 
  archive: /archives
  #works: /demo
  #music: /music
  about: /about
  github:
    name: Github
    link: https://github.com/fatherai
    icon: icon-github

highlight_theme: normal

loader_img: http://oo12ugek5.bkt.clouddn.com/blog/images/loader.gif